spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/sns
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

app:
  domain:
    url: http://your-frontend-domain

jwt:
  expiration: 86400000  # 24시간
  secret: ${JWT_SECRET:c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK}

springdoc:
  api-docs:
    enabled: true  # API 문서 활성화
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접근 경로
    operationsSorter: method  # API 문서에서 HTTP 메서드 정렬
    tagsSorter: alpha  # API 태그 알파벳 정렬
    display-request-duration: true  # 요청 처리 시간 표시
